### PR TITLE
add support for multiple scala versions

### PR DESCRIPTION
**Pull request by tdyas**
Add support for multiple Scala versions by using two resolves, one for each Scala version. Scalac plugins are defined per resolve so that the version of the `acyclic` plugin matches the Scala version used for the resolve.

The resolves are `jvm-default` with Scala 2.13.8 and `scala-2.12` with Scala 2.12.15.

### CODE REVIEW

**Comment by stuhood** [comment]
Looks great: thanks. Getting https://github.com/pantsbuild/pants/issues/14493 resolved for the relevant cases will be really important to cut down the boilerplate here.

**Comment by stuhood** [comment]
I've updated this to use `parametrize` in a few spots, and opened https://github.com/pantsbuild/pants/issues/13882#issuecomment-1042576097 to summarize the TODOs.

**Comment by stuhood** [comment]
While we should maintain this PR (and continue to reduce boilerplate in it whenever possible via new `parametrize` changes, etc), I don't think that we should merge it.

**Comment by tdyas** [comment]
> While we should maintain this PR (and continue to reduce boilerplate in it whenever possible via new `parametrize` changes, etc), I don't think that we should merge it.

Or maybe maintain a branch on the upstream with this support? (And have some automation to update Scala versions and run CI against it.)

**Pull request closed without merging**
